version: "3.9"

services:
  laravel:
    build: .
    env_file:
      - .env.dev
    volumes:
      - .:/var/www/html
      - app-storage:/var/www/html/storage
      - app-cache:/var/www/html/bootstrap/cache
    ports:
      - "8082:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  app-storage:
  app-cache:

